### ISSUE TITLE
Pausing moving words

### ISSUE THREAD

**Issue by chaitanyamalaviya** [revueltai/movinwords#2]
Hi, thank you for releasing this great package!

I wanted to add a feature to pause the animation when the user isn't actively viewing the page.

I was considering implementing a method called pause() inside the main `Movinwords` class and calling it when the document is hidden. I'm not so sure how to implement this method so that the animation is frozen when the user leaves the page. 
Do you have any suggestions for how to proceed?

Thanks!

**Comment by revueltai** [comment]
Hello!
Sorry for the very late reply.

Pausing is not doable at the moment 😞 . 
Movinwords uses css-transitions and those cannot be directly paused, as CSS does not provide a specific property or command to pause a running transition.

It could potentially be implemented on the code's side, but this is also tricky, as the code would need to know in advance which transition props to pause/resume based on the "transition" (fadeIn, slideIn, etc) that is provided.

**Comment by revueltai** [comment]
Quick update:
The pause logic has been implemented:
https://github.com/revueltai/movinwords?tab=readme-ov-file#pause
