### ISSUE TITLE
Svelte

### ISSUE THREAD

**Issue by louislugas** [revueltai/movinwords#3]
any guidance to use it on svelte? it appears I can't import the css file.

this is my REPL:
https://svelte.dev/repl/9cf34a2c177e4f33a929a174c775ed62?version=3.49.0

**Comment by revueltai** [comment]
Hi!
I am not very familiarized with Svelte, but I prepared this example based on this [link](https://svelte.dev/repl/28f4b2e36e4244b8b23cae3d584c4c88?version=3.53.1)

```
<script>	
	const init = () => {
		const myInstance = new Movinwords({
			el: '.demo',
			autostart: false,
			wordSpacing: 20,
			duration: 500,
			offset: 100,
			transition: 'revealInBottom'
		});	
		
		setTimeout(() => myInstance.start(), 2000)
	}
</script>

<div class="demo">TEXT TO ANIMATE</div>

<svelte:head>
<script src="https://unpkg.com/movinwords/movinwords.min.js" on:load={init}></script>	
<link rel="stylesheet" href="https://unpkg.com/movinwords/movinwords.css">
</svelte:head>
```

Hope it helps!
