### ISSUE TITLE
[BUG] end event not being fired if last word is more than one character

### ISSUE THREAD

**Issue by noise-cd** [revueltai/movinwords#4]
### Current behavior (A clear and concise description of what you saw.)
end event is not fired if the last word is greater than 1 character

### Expected behavior (A clear and concise description of what you expected to happen.)
end event should be fired when the last word has greater than 1 character

### Steps to reproduce (1- Go to '...' / 2- Click on '....' / 3- Scroll down to '....' / 4- See error)
Change the last word used within the selected el to contain more than one character. Look for end function being fired within the console. Event 'end' is fired with a single character, event 'end' is not fired when greater than one character

### Platform
- [x] Desktop   
- [x] Mobile

### Browser and/or Device version
Mac OS Ventura 13.0.1 - firefox 107

### Other Information
Your sandbox works as expected but you are only using a single emoji/letter. If you change the last word to have more than one character the end event is not fired. 

This is caused by word.innerText passing the word with newline \n between each character e.g. the word test is passed to _isLastWordOfSentence as 
 t\n
 e\n
 s\n
 t  
 on line 262 https://github.com/revueltai/movinwords/blob/main/package/movinwords.js

you could rectify this by changing 
if (this._isLastWordOfSentence(word.innerText))  
to 
if (this._isLastWordOfSentence(word.textContent)) {
which would pass the word without the new lines

**Comment by revueltai** [comment]
Hi! 👋 
This has been addressed in v1.1.0.
https://github.com/revueltai/movinwords/blob/main/package/movinwords.js#L262

Can you confirm if this has solved the bug?
Thanks!

**Comment by noise-cd** [comment]
Hi 

I can confirm working for us in v1.10 👍

Many thanks
